name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: ['22.x']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install NPM Dependencies
        run: npm install

      - name:  Build & Publish
        run: npm run publish-mac
        env:
          VITE_LSP_WEBSOCKET_PORT: 54331
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install NPM Dependencies
        run: npm install

      - name: install dependencies
        run: sudo apt-get install -y libgtk-3-0 libnss3 libxss1 libasound2 snapd
        
      - name: Installk snapcraft
        run: sudo snap install snapcraft --classic

      - name: Install AppImage
        run: sudo apt-get install -y fuse  

      - name: 🐧 Build & Publish AppImage
        run: npm run publish-linux -- AppImage
        env:
          VITE_LSP_WEBSOCKET_PORT: 54331
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ['22.x']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install NPM Dependencies
        run: npm install

      - name: 🪟 Build & Publish
        run: npm run publish-win
        env:
          VITE_LSP_WEBSOCKET_PORT: 54331
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}